### ISSUE TITLE
requireNativeComponent: "PinchableView" was not found in the UIManager.

### ISSUE THREAD

**Issue by Choyeongdeok** [oblador/react-native-pinchable#4]
npm i react-native-pinchable
cd ios && pod install

import Pinchable from 'react-native-pinchable'

<Pinchable>
...
</Pinchable>

then I got an error
'requireNativeComponent: "PinchableView" was not found in the UIManager.'
how can I solve it?

**Comment by blindvalentine** [comment]
Hi, any solution for this?

**Comment by jirizikmund** [comment]
> npm i react-native-pinchable cd ios && pod install
> 
> import Pinchable from 'react-native-pinchable'
> 
> ...
> then I got an error 'requireNativeComponent: "PinchableView" was not found in the UIManager.' how can I solve it?

After `pod install` you need to rebuild you app (`npx react-native run-ios` or manually in Xcode)

**Comment by Prashanth-K-25** [comment]
npm i react-native-pinchable

import Pinchable from 'react-native-pinchable'

...
then I got an error
'requireNativeComponent: "PinchableView" was not found in the UIManager.'
how can I solve it?
